---
deployment:
  tasks:
    - export DEPLOYPATH=/home/autovoic/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp privacy.html $DEPLOYPATH
    - /bin/cp terms.html $DEPLOYPATH
    - /bin/cp submit.php $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
